-- ============================================================================
-- GENERADOR MASIVO DE 2000 REGISTROS CHILENOS (LIMPIOS Y SUCIOS MEZCLADOS)
-- ============================================================================

-- 1. Creamos la tabla sin restricciones estrictas para poder guardar los errores
DROP TABLE IF EXISTS pacientes_medisalud;

CREATE TABLE pacientes_medisalud (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100),
    edad INT,
    correo VARCHAR(150),
    telefono VARCHAR(50),
    ciudad VARCHAR(100),
    fecha_nacimiento VARCHAR(50) 
);

-- 2. Inserción matemática de 2000 filas con inyección de errores aleatorios
INSERT INTO pacientes_medisalud (nombre, edad, correo, telefono, ciudad, fecha_nacimiento)
WITH matriz_aleatoria AS (
    SELECT
        x AS correlativo,
        RAND() AS probabilidad_error,                 -- Determina si la fila tendrá un error
        CAST(FLOOR(RAND() * 6) + 1 AS INT) AS tipo_error, -- Qué regla de negocio va a romper
        CAST(FLOOR(RAND() * 20) + 1 AS INT) AS n_idx,  -- Índice para nombres
        CAST(FLOOR(RAND() * 20) + 1 AS INT) AS a_idx,  -- Índice para apellidos
        CAST(FLOOR(RAND() * 10) + 1 AS INT) AS c_idx,  -- Índice para ciudades
        CAST(FLOOR(RAND() * 65) + 18 AS INT) AS edad_ok -- Edad base válida (18 a 83)
    FROM SYSTEM_RANGE(1, 2000) -- Genera exactamente 2000 filas
),
datos_base AS (
    SELECT
        correlativo, probabilidad_error, tipo_error, edad_ok,
        CASE n_idx
            WHEN 1 THEN 'Juan' WHEN 2 THEN 'María' WHEN 3 THEN 'Pedro' WHEN 4 THEN 'Diego' WHEN 5 THEN 'Francisca'
            WHEN 6 THEN 'Javiera' WHEN 7 THEN 'Camila' WHEN 8 THEN 'Gonzalo' WHEN 9 THEN 'Felipe' WHEN 10 THEN 'Valentina'
            WHEN 11 THEN 'Matías' WHEN 12 THEN 'Constanza' WHEN 13 THEN 'Sebastián' WHEN 14 THEN 'Antonia' WHEN 15 THEN 'Nicolás'
            ELSE 'Alejandro'
        END AS nom,
        CASE a_idx
            WHEN 1 THEN 'Pérez' WHEN 2 THEN 'Soto' WHEN 3 THEN 'González' WHEN 4 THEN 'Muñoz' WHEN 5 THEN 'Rojas'
            WHEN 6 THEN 'Díaz' WHEN 7 THEN 'Silva' WHEN 8 THEN 'Contreras' WHEN 9 THEN 'Olivares' WHEN 10 THEN 'Flores'
            ELSE 'Sepúlveda'
        END AS ape,
        CASE c_idx
            WHEN 1 THEN 'Santiago' WHEN 2 THEN 'Valparaíso' WHEN 3 THEN 'Concepción' WHEN 4 THEN 'La Serena'
            WHEN 5 THEN 'Antofagasta' WHEN 6 THEN 'Temuco' WHEN 7 THEN 'Rancagua' ELSE 'Talca'
        END AS ciu
    FROM matriz_aleatoria
)
SELECT
    -- Regla 1: Nombre obligatorio (Se vuelve NULL si cae en el 4% de error)
    CASE WHEN probabilidad_error < 0.04 AND tipo_error = 1 THEN NULL ELSE nom || ' ' || ape END AS nombre,

    -- Regla 2: Edad 0-120 (Inyecta edades negativas o gigantes en el 4% de los casos)
    CASE 
        WHEN probabilidad_error >= 0.04 AND probabilidad_error < 0.08 AND tipo_error = 2 THEN -12
        WHEN probabilidad_error >= 0.04 AND probabilidad_error < 0.08 AND tipo_error = 3 THEN 145
        ELSE edad_ok 
    END AS edad,

    -- Regla 3: Correo con @ (Quita el '@' en el 4% de los casos)
    CASE 
        WHEN probabilidad_error >= 0.08 AND probabilidad_error < 0.12 AND tipo_error = 4 THEN LOWER(nom) || LOWER(ape) || correlativo || 'gmail.com'
        ELSE LOWER(nom) || '.' || LOWER(ape) || correlativo || '@gmail.com' 
    END AS correo,

    -- Regla 4: Teléfono de exactamente 9 dígitos (Crea números cortos o largos al azar)
    CASE 
        WHEN probabilidad_error >= 0.12 AND probabilidad_error < 0.16 AND tipo_error = 5 THEN '12345'
        WHEN probabilidad_error >= 0.12 AND probabilidad_error < 0.16 AND tipo_error = 6 THEN '987654321001'
        ELSE '9' || CAST(FLOOR(RAND() * 90000000) + 10000000 AS INT) 
    END AS telefono,

    -- Regla 5: Ciudad obligatoria (Se vuelve NULL en el 3% de los casos)
    CASE WHEN probabilidad_error >= 0.16 AND probabilidad_error < 0.19 AND tipo_error = 1 THEN NULL ELSE ciu END AS ciudad,

    -- Regla 6: Fecha de nacimiento no futura (Pone año 2035 en el 3% de los casos)
    CASE 
        WHEN probabilidad_error >= 0.19 AND probabilidad_error < 0.22 AND tipo_error = 2 THEN '2035-12-25'
        ELSE CAST(DATEADD(YEAR, -edad_ok, CURRENT_DATE) AS VARCHAR) 
    END AS fecha_nacimiento
FROM datos_base;
